#!/bin/sh
name=$(basename ${1%.*})
libs=$(find lib -name *.a)
python3 main.py $1 > output/$name.asm &&
fasm output/$name.asm output/$name.o > /dev/null &&
ld -o output/$name output/$name.o $libs -static &&
output/$name
